my final commit
Clementify/LESS0N3_TASK5_OBI_CLEMENTINA pull request #1
Opened 2023-05-25 12:12 UTC by Clementify

I am done with my work please review @ChidiPatrick and @Promise-J.
Group-B.

2023-05-25 15:27 UTC, promise-J requested changes
Just one change to make. Please make the header nav links not to over-flow. 
Let it have a good font-size as it should please

2023-05-25 15:58 UTC, ChidiPatrick requested changes
Nice layout. Please close all your image tag properly, and make the header title responsive

2023-05-25 15:58 UTC, ChidiPatrick commented on index.html
> +                <img src="./images/male2.jfif" alt="male2">
Close you image tags

2023-05-25 15:58 UTC, ChidiPatrick commented on index.html
> +            <img src="./images/logo main.png" alt="logo">
close your tag

2023-05-25 15:58 UTC, ChidiPatrick commented on index.html
> +                <img src="./images/male4.jfif" alt="male wears">
close the tag

2023-05-25 16:13 UTC, ChidiPatrick approved these changes
Great job! You can now merge

2023-05-26 12:11 UTC, Clementify commented
> Just one change to make. Please make the header nav links not to over-flow. Let it have a good font-size as it should please

Done sir, Thank you.

2023-05-26 12:11 UTC, merged